#spring:
# datasource:
#  username: root
#  password: mansoor222801
#  url: dbc:mysql:// localhost:3306/crudapp
#  driver-class-name: com.mysql.cj.jdbc.Driver
# jpa:
#  show-sql: true
#  hibernate:
#   dd1-auto: update
#  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect